CREATE TABLE `projeto_db`.`cliente` ( `id` INT NULL AUTO_INCREMENT , `nome` VARCHAR(250) NULL , `rg` VARCHAR(10) NOT NULL , `CPFCNPJ` VARCHAR(11) NOT NULL , `DtNasc` VARCHAR(8) NOT NULL , `endereco` VARCHAR(255) NOT NULL , `numEndereco` VARCHAR(5) NOT NULL , `bairro` INT NOT NULL , `tipo` CHAR NULL DEFAULT 'F' , `ex` BOOLEAN NULL DEFAULT FALSE , PRIMARY KEY (`id`)) ENGINE = InnoDB;

